/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::PinnedAssetImage GroundTiles;
extern const Sifteo::AssetImage BlackTile;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
