/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::PinnedAssetImage Pikachu;
extern const Sifteo::PinnedAssetImage GroundTiles;
extern const Sifteo::AssetImage HorizontalWall;
extern const Sifteo::AssetImage IsHere;
extern const Sifteo::AssetImage VerticalWall;
extern const Sifteo::PinnedAssetImage Plants;
extern const Sifteo::AssetImage BlackTile;
extern Sifteo::AssetGroup CatAssets;
extern const Sifteo::PinnedAssetImage Cat;
